const minutesAgo = (minutes) => new Date(Date.now() - minutes * 60_000).toISOString()

export const CATEGORY_LIST = [
  {
    id: 'innovation',
    label: 'Innovation',
    short: 'Innov.',
    icon: 'Lightbulb',
    color: '#2dd4bf',
    glow: 'rgba(45, 212, 191, .32)',
    prompt: 'rupture, nouveaux services, transformation des usages',
  },
  {
    id: 'durabilite',
    label: 'Durabilite',
    short: 'Impact',
    icon: 'Leaf',
    color: '#22c55e',
    glow: 'rgba(34, 197, 94, .28)',
    prompt: 'climat, ressources, economie circulaire, impact responsable',
  },
  {
    id: 'collaboration',
    label: 'Collaboration',
    short: 'Collectif',
    icon: 'Handshake',
    color: '#f59e0b',
    glow: 'rgba(245, 158, 11, .30)',
    prompt: 'ecosystemes, partenaires, reseaux, intelligence collective',
  },
  {
    id: 'technologie',
    label: 'Technologie',
    short: 'Tech',
    icon: 'Cpu',
    color: '#38bdf8',
    glow: 'rgba(56, 189, 248, .30)',
    prompt: 'IA, donnees, automatisation, plateformes numeriques',
  },
  {
    id: 'humain',
    label: 'Humain',
    short: 'Humain',
    icon: 'UsersRound',
    color: '#f472b6',
    glow: 'rgba(244, 114, 182, .28)',
    prompt: 'inclusion, competences, education, experience utilisateur',
  },
  {
    id: 'futur',
    label: 'Futur',
    short: '2030',
    icon: 'Rocket',
    color: '#a78bfa',
    glow: 'rgba(167, 139, 250, .30)',
    prompt: 'prospective, smart city, nouveaux modeles, vision 2030',
  },
]

export const CATS = CATEGORY_LIST.reduce((acc, category) => {
  acc[category.id] = category
  return acc
}, {})

export const SENT_COLOR = {
  positif: '#22c55e',
  neutre: '#94a3b8',
  negatif: '#fb7185',
}

export const POS_WORDS = [
  'ameliorer',
  'avenir',
  'bien',
  'collabor',
  'confiance',
  'creer',
  'developper',
  'durable',
  'efficace',
  'excellent',
  'impact',
  'inclusif',
  'innovation',
  'innover',
  'opportunite',
  'partage',
  'positif',
  'progres',
  'solution',
  'utile',
  'valoriser',
]

export const NEG_WORDS = [
  'attention',
  'biais',
  'bloquant',
  'contraignant',
  'danger',
  'difficile',
  'echec',
  'erreur',
  'inegalite',
  'lent',
  'mauvais',
  'mefiance',
  'probleme',
  'risque',
  'trop',
]

export const STOP_WORDS = [
  'alors',
  'avec',
  'avoir',
  'cette',
  'dans',
  'des',
  'donc',
  'elle',
  'etre',
  'faire',
  'leur',
  'mais',
  'nous',
  'plus',
  'pour',
  'que',
  'qui',
  'sans',
  'sont',
  'sur',
  'tout',
  'une',
  'vous',
]

export const DEFAULT_CONFIG = {
  layout: 'mosaic',
  rotationSpeed: 8,
  showBanner: true,
  showLogo: true,
  primaryColor: '#2dd4bf',
  accentColor: '#7c3aed',
  colorMode: 'dark',
  theme: 'digital',
  eventName: 'Innovation 2030 - SOFTWELL',
  requireActivation: true,
  activationCode: '2030',
  autoModeration: true,
  aiProvider: {
    mode: 'proxy',
    apiBaseUrl: 'https://api.openai.com/v1',
    model: 'gpt-4o-mini',
    imageModel: 'gpt-image-1-mini',
    generateImages: true,
    apiKey: '',
    timeoutMs: 14_000,
  },
}

export const DEMO_DATA = {
  events: [
    {
      id: 'e1',
      name: 'Innovation 2030 - SOFTWELL',
      description: 'Un mur interactif pour capter les idees, analyser les tendances et inspirer la roadmap.',
      theme: 'digital',
      isActive: true,
      createdAt: minutesAgo(240),
      endDate: new Date(Date.now() + 20 * 24 * 60 * 60_000).toISOString(),
    },
  ],
  contributions: [
    {
      id: 'c1',
      eventId: 'e1',
      pseudonym: 'Rina',
      text: "L'IA devrait aider les medecins a diagnostiquer plus vite, surtout dans les zones rurales.",
      category: 'technologie',
      aiTheme: 'Sante digitale',
      sentiment: 'positif',
      keywords: ['medecins', 'diagnostiquer', 'rurales'],
      relevanceScore: 92,
      reactions: { like: 8, fire: 5, heart: 3 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: true,
      createdAt: minutesAgo(52),
      aiProvider: 'demo',
      aiSummary: 'La contribution pousse une IA de sante plus accessible et utile au diagnostic.',
      visualPrompt: 'Interface medicale futuriste, reseau de cliniques rurales connectees, couleurs cyan et vert.',
    },
    {
      id: 'c2',
      eventId: 'e1',
      pseudonym: 'Jean',
      text: "Developper des energies renouvelables accessibles pour tous les pays en developpement d'ici 2030.",
      category: 'durabilite',
      aiTheme: 'Energie inclusive',
      sentiment: 'positif',
      keywords: ['energies', 'renouvelables', 'developpement'],
      relevanceScore: 88,
      reactions: { like: 6, fire: 7, heart: 4 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: false,
      createdAt: minutesAgo(47),
      aiProvider: 'demo',
      aiSummary: "Une idee d'acces equitable a l'energie propre.",
      visualPrompt: 'Micro-reseaux solaires, village connecte, lumiere verte et ambre.',
    },
    {
      id: 'c3',
      eventId: 'e1',
      pseudonym: 'Lalao',
      text: 'Creer des plateformes collaboratives pour connecter les startups africaines aux marches mondiaux.',
      category: 'collaboration',
      aiTheme: 'Ecosysteme startup',
      sentiment: 'positif',
      keywords: ['plateformes', 'startups', 'marches'],
      relevanceScore: 85,
      reactions: { like: 4, fire: 2, heart: 6 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: false,
      createdAt: minutesAgo(42),
      aiProvider: 'demo',
      aiSummary: 'La contribution vise une plateforme de mise en relation internationale.',
      visualPrompt: 'Carte numerique de partenariats, hubs africains, lignes lumineuses.',
    },
    {
      id: 'c4',
      eventId: 'e1',
      pseudonym: 'Marc',
      text: "L'education doit se reinventer avec gamification, apprentissage adaptatif et competences du futur.",
      category: 'humain',
      aiTheme: 'Education augmentee',
      sentiment: 'positif',
      keywords: ['education', 'gamification', 'competences'],
      relevanceScore: 90,
      reactions: { like: 10, fire: 3, heart: 8 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: true,
      createdAt: minutesAgo(36),
      aiProvider: 'demo',
      aiSummary: 'Une vision de formation continue plus ludique et personnalisee.',
      visualPrompt: 'Salle immersive, avatars apprenants, parcours de competences lumineux.',
    },
    {
      id: 'c5',
      eventId: 'e1',
      pseudonym: 'Soa',
      text: 'Automatiser les taches repetitives pour liberer du temps vers des missions a valeur humaine.',
      category: 'innovation',
      aiTheme: 'Futur du travail',
      sentiment: 'positif',
      keywords: ['automatiser', 'repetitives', 'humaine'],
      relevanceScore: 87,
      reactions: { like: 5, fire: 6, heart: 2 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: false,
      createdAt: minutesAgo(31),
      aiProvider: 'demo',
      aiSummary: "L'automatisation est positionnee comme levier de qualite de travail.",
      visualPrompt: 'Tableau de bord robotique discret, humains creatifs au centre.',
    },
    {
      id: 'c6',
      eventId: 'e1',
      pseudonym: 'Hery',
      text: 'Blockchain pour tracer les chaines alimentaires et garantir la provenance des produits.',
      category: 'technologie',
      aiTheme: 'Tracabilite',
      sentiment: 'neutre',
      keywords: ['blockchain', 'alimentaires', 'provenance'],
      relevanceScore: 78,
      reactions: { like: 3, fire: 1, heart: 1 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: false,
      createdAt: minutesAgo(27),
      aiProvider: 'demo',
      aiSummary: 'Une piste technique pour renforcer confiance et transparence.',
      visualPrompt: 'Chaine logistique alimentaire, blocs de donnees, capteurs bleus.',
    },
    {
      id: 'c7',
      eventId: 'e1',
      pseudonym: 'Vola',
      text: 'Mettre fin a la fracture numerique avec internet haut debit et appareils abordables.',
      category: 'humain',
      aiTheme: 'Inclusion digitale',
      sentiment: 'positif',
      keywords: ['fracture', 'numerique', 'abordables'],
      relevanceScore: 91,
      reactions: { like: 7, fire: 4, heart: 5 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: false,
      createdAt: minutesAgo(22),
      aiProvider: 'demo',
      aiSummary: "L'idee cible l'acces universel aux outils numeriques.",
      visualPrompt: 'Communautes connectees, tablettes accessibles, halo rose et cyan.',
    },
    {
      id: 'c8',
      eventId: 'e1',
      pseudonym: 'Koto',
      text: 'Les villes intelligentes doivent integrer des espaces verts et des mobilites douces par defaut.',
      category: 'futur',
      aiTheme: 'Smart city responsable',
      sentiment: 'positif',
      keywords: ['villes', 'intelligentes', 'mobilites'],
      relevanceScore: 83,
      reactions: { like: 4, fire: 3, heart: 4 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: false,
      createdAt: minutesAgo(18),
      aiProvider: 'demo',
      aiSummary: 'Une proposition de ville connectee mais respirable.',
      visualPrompt: 'Ville 2030, pistes cyclables lumineuses, jardins verticaux.',
    },
    {
      id: 'c9',
      eventId: 'e1',
      pseudonym: 'Tina',
      text: 'Trop de promesses technologiques sans resultats concrets. Il faut des standards mesurables.',
      category: 'innovation',
      aiTheme: 'Gouvernance tech',
      sentiment: 'negatif',
      keywords: ['promesses', 'technologiques', 'standards'],
      relevanceScore: 65,
      reactions: { like: 2, fire: 1, heart: 0 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: false,
      createdAt: minutesAgo(14),
      aiProvider: 'demo',
      aiSummary: "Signal critique sur la necessite d'indicateurs et de preuves d'impact.",
      visualPrompt: 'Tableau de bord de gouvernance, signaux orange, preuves et indicateurs.',
    },
    {
      id: 'c10',
      eventId: 'e1',
      pseudonym: 'Fidy',
      text: 'Valoriser les savoir-faire locaux avec le numerique pour preserver la culture malgache.',
      category: 'collaboration',
      aiTheme: 'Culture digitale',
      sentiment: 'positif',
      keywords: ['savoir-faire', 'numerique', 'culture'],
      relevanceScore: 80,
      reactions: { like: 6, fire: 2, heart: 7 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: false,
      createdAt: minutesAgo(10),
      aiProvider: 'demo',
      aiSummary: 'La numerisation devient un canal de transmission culturelle.',
      visualPrompt: 'Artisanat local scanne en 3D, galerie numerique, reseau dore.',
    },
    {
      id: 'c11',
      eventId: 'e1',
      pseudonym: 'Rojo',
      text: 'Attention aux biais algorithmiques qui reproduisent les inegalites sociales a grande echelle.',
      category: 'humain',
      aiTheme: 'Ethique IA',
      sentiment: 'negatif',
      keywords: ['biais', 'algorithmiques', 'inegalites'],
      relevanceScore: 72,
      reactions: { like: 3, fire: 2, heart: 1 },
      imageUrl: '',
      status: 'pending',
      isHighlighted: false,
      createdAt: minutesAgo(7),
      aiProvider: 'demo',
      aiSummary: 'Alerte ethique sur les risques de reproduction des biais.',
      visualPrompt: 'Balance ethique, reseaux neuronaux sous audit, contraste rose et gris.',
    },
    {
      id: 'c12',
      eventId: 'e1',
      pseudonym: 'Niry',
      text: "Creer un fonds mondial pour financer l'innovation dans les pays les moins avances.",
      category: 'futur',
      aiTheme: 'Finance inclusive',
      sentiment: 'neutre',
      keywords: ['fonds', 'financer', 'innovation'],
      relevanceScore: 76,
      reactions: { like: 4, fire: 1, heart: 3 },
      imageUrl: '',
      status: 'visible',
      isHighlighted: false,
      createdAt: minutesAgo(4),
      aiProvider: 'demo',
      aiSummary: "Une mecanique de financement pour accelerer l'innovation inclusive.",
      visualPrompt: 'Flux financiers mondiaux, startup labs, horizon violet et cyan.',
    },
  ],
  adminUser: { username: 'admin', password: 'admin123' },
  displayConfig: DEFAULT_CONFIG,
  session: { isAdminLoggedIn: false, currentEventId: 'e1' },
}
